### PR TITLE
Fix #20 Create LICENSE

### LINKED ISSUE #20: license clarification request
I don't see a license reference in the repository.

Are you considering this derivative of Blender -> GPL ?

Are you licensing this in some more permissive license, such as LGPL or BSD 3-Clause which will still allow it to be pulled upstream?

### PR DESCRIPTION
**Pull request by Blendify**
Fix #20 Adds The Unlicense http://unlicense.org/

### CODE REVIEW

**Comment by sobotka** [comment]
Hopefully license isn’t required here.

**Comment by cesss** [comment]
> Hopefully license isn’t required here.

I'm considering adding your LUTs to another software project, so I believe it does make sense to clarify the license (unless the LUTs are publicly available elsewhere... are they your own work, or did you get them from some place?)

**Comment by sobotka** [comment]
It’s up to you.

While adding a license can aid on one front, it also somewhat passively implies that people can exert claims over numbers. I’m not going to do that and legitimate the various companies that have tried. It’s the wrong approach.

**Comment by cesss** [comment]
Thanks!

**Pull request closed without merging**
